services:
  talentoplus.api:
    image: talentoplus.api
    build:
      context: .
      dockerfile: src/TalentoPlus.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - talentoplus-network
  
  talentoplus.frontend:
    image: talentoplus.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - talentoplus.api
    networks:
      - talentoplus-network

networks:
  talentoplus-network:
    driver: bridge